Donate page
himanshu007-creator/SFC-foundations pull request #232
Opened 2021-05-01 09:42 UTC by nidhivanjare

# Description

Front end for donate page. 

Fixes #224

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system: MAC OS
* Version: 11.2.3
* Text-editors used: vscode
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS

<img width="1440" alt="Screenshot 2021-05-01 at 3 10 59 PM" src="https://user-images.githubusercontent.com/55665104/116778433-7aaaef00-aa8f-11eb-8a6f-08f0e6ed3c6e.png">

<img width="1440" alt="Screenshot 2021-05-01 at 3 11 11 PM" src="https://user-images.githubusercontent.com/55665104/116778436-7e3e7600-aa8f-11eb-8572-d733f8cf845d.png">

2021-05-01 09:45 UTC, rohank2502 commented
Please Deploy github pages  @nidhivanjare

2021-05-01 14:39 UTC, himanshu007-creator commented
> Please Deploy github pages @nidhivanjare

yes @nidhivanjare , after that , it will be easier to work

2021-05-02 09:10 UTC, nidhivanjare commented
https://nidhivanjare.github.io/SFC-foundations/

DONE!!

2021-05-03 07:54 UTC, rohank2502 commented
@himanshu007-creator  Please give it a look the Navbar is not like other pages should we go for this? And @nidhivanjare  I think we should add a link to every three projects because when we click project we get to head over to the home page and from that is user has to navigate own it on then we cant name the button projects we can rather add links to a page of each project in the name itself !!

2021-05-04 10:11 UTC, nidhivanjare commented
I have added the project link 

Please let me know about the navbar though !!

2021-05-05 09:45 UTC, nidhivanjare commented
@rohank2502. ??

2021-05-06 09:14 UTC, nidhivanjare commented
@himanshu007-creator will you merge this brach or let me know any changes that I have to make ??

2021-05-06 10:39 UTC, himanshu007-creator commented
> @himanshu007-creator will you merge this branch or let me know any changes that I have to make ??

Please share the github page link. opened your latest deployment from <a href="https://github.com/nidhivanjare/SFC-foundations/deployments/activity_log?environment=github-pages">here</a> but the donate page showed error. Please look into it

2021-05-06 10:48 UTC, himanshu007-creator requested changes

2021-05-06 10:48 UTC, himanshu007-creator commented on index.html
> +                <li><a href="../../Assets/Donate.html">DONATE</a></li>
<code>./Assets/Donate.html</code>
Try to change href with this and recheck all other links as well.

2021-05-06 13:40 UTC, nidhivanjare commented
DONE!!

2021-05-07 18:31 UTC, himanshu007-creator requested changes
Its good to merge, just some minor changes

1) Favicon is not showing in the page. See other page for it.
2) the slideshow you created is probably broken, or if this is your idea , i dont get it.

you have done a good job. 1st problem is an easy fix, but the 2ns one needs some work. What i infer is that you want to make a slideshow. like this <a href="https://www.w3schools.com/w3css/w3css_slideshow.asp">example</a>. But its broken and thats why page behaves in a unusual way.

2021-05-08 04:55 UTC, nidhivanjare commented
I will fix it and get back to you!!

2021-05-08 10:16 UTC, nidhivanjare commented
Done @himanshu007-creator

2021-05-09 05:57 UTC, nidhivanjare commented
Done @himanshu007-creator

Any other changes?

2021-05-10 10:08 UTC, nidhivanjare commented
> Done @himanshu007-creator
> 
> Any other changes?

??

2021-05-10 10:10 UTC, himanshu007-creator commented
> > Done @himanshu007-creator
> > Any other changes?
> 
> ??

nope, just resolve the conflicts

2021-05-10 10:13 UTC, himanshu007-creator commented
> yes , i did just now

https://nidhivanjare.github.io/SFC-foundations/Assets/Donate.html#
still favicon is not there😬

2021-05-10 10:18 UTC, nidhivanjare commented
<img width="1329" alt="Screenshot 2021-05-10 at 3 48 08 PM" src="https://user-images.githubusercontent.com/55665104/117644467-20a0dc80-b1a7-11eb-971f-f3638bf21b2a.png">


You don't mean this ??

2021-05-10 10:19 UTC, nidhivanjare commented
okay so I was using safari and there was no favicon there, I understood now !! 
will do right away

2021-05-10 10:22 UTC, nidhivanjare commented
DONE

2021-05-10 10:40 UTC, himanshu007-creator commented
Thanks a lot for your contribution @nidhivanjare 🎉✨

2021-05-10 10:40 UTC, merged