Updated Contributing .md file
himanshu007-creator/SFC-foundations pull request #284
Opened 2021-05-19 18:24 UTC by mansijain980

# Description

I have modified the contributing.md file to make it readable and efficient .

Fixes #39 

 
# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-05-19 18:56 UTC, mansijain980 commented
@himanshu007-creator this issue will count under gssoc'21 ?

2021-05-20 04:07 UTC, rohank2502 commented
> 
> 
> @himanshu007-creator this issue will count under gssoc'21 ?

Don't worry this will count

2021-05-20 04:09 UTC, rohank2502 requested changes
Line 29: Change Repo to Repository

2021-05-20 04:17 UTC, himanshu007-creator commented on CONTRIBUTING.md
> +### Step 1 : Fork the Repo😆
replace the emoji with 🔗

2021-05-20 04:18 UTC, himanshu007-creator requested changes
And replace repo with repository as suggested by @rohank2502

2021-05-20 07:40 UTC, merged